image: docker:stable

stages:
  - test

frontend_lint:
  stage: test
  image: node:10-alpine
  before_script:
    - 'echo "export const VERSION_INFO = { ciCommitTag: ''$CI_COMMIT_TAG'' };" > ./frontend/src/VERSION.js'
  script:
    - cd frontend
    - yarn install
    - yarn lint
