image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test
  - deploy

before_script:
  - 'echo "export const VERSION_INFO = { ciCommitTag: ''$CI_COMMIT_TAG'' };" > ./frontend/src/VERSION.js'

frontend_lint:
  stage: test
  image: node:10-alpine
  only:
    changes:
      - frontend/**/*
  script:
    - cd frontend
    - yarn install
    - yarn lint

deploy_to_docker_hub:
  stage: deploy
  when: manual
  only:
    # We only want master branch AND when tag looks like 'vX.Y.Z', however GitLab doesn't support conjunctive conditions yet:
    #   https://gitlab.com/gitlab-org/gitlab-ce/issues/27818
    # refs:
    #   - master  # Yeah, that doesn't work... The job for a commit with a tag and on a master branch is not being created.
    #
    # However we can mark tags 'v*.*.*' as protected, which also allows us to (somewhat) safely use Private-Token as protected
    # CI variable.
    variables:
      - $CI_COMMIT_TAG =~ /^v[0-9]+[.][0-9]+[.][0-9]+$/
  script:
    - apk add --no-cache git curl jq
    # check that we are deploying the latest version:
    - export LAST_KNOWN_VERSION=`git tag -l --sort=-version:refname "v*.*.*" | head -n 1 | tr -d '[:space:]'`
    - '[ "$LAST_KNOWN_VERSION" == "$CI_COMMIT_TAG" ] || (echo "Tag does not denote latest known version (which is $LAST_KNOWN_VERSION), aborting!" && exit 1)'
    # automatically create frontend/CHANGELOG.json from GitLab tags:
    - 'curl -H "Private-Token: $GITLAB_API_ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/grafolean%2Fgrafolean/repository/tags" > /tmp/tags.json'
    - 'cat /tmp/tags.json | jq ''[.[].release | select(.tag_name | test("^v[0-9]+[.][0-9]+[.][0-9]+$")) | { version: .tag_name, changelog: .description }]'' > frontend/CHANGELOG.json'
    - echo "Deploying..."
    - cp ./install/docker-compose/Dockerfile .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker rmi grafolean/grafolean:$CI_COMMIT_TAG
    - docker rmi grafolean/grafolean:latest
