version: '2.1'
services:

  db:
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_DB=grafolean
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -U admin -t 1 -q"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /tmp/db/:/var/lib/postgresql/data/

    networks:
      - grafolean

  mosquitto:
    image: grafolean/mosquitto
    ports:
      - "1883:1883"
      - "9883:9883"
    networks:
      - grafolean

  grafolean:
    # This is a hack to make Mosquitto work in this setting:
    # Mosquitto uses our REST API for auth, but it assumes it is available on hostname grafolean, port 80. Instead
    # of changing mosquitto settings (which would be cleaner, but more challenging) we simply provide another
    # backend at the correct address:
    image: grafolean/grafolean
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_DATABASE=grafolean
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - MQTT_HOSTNAME=mosquitto
      - MQTT_PORT=1883
      - MQTT_WS_HOSTNAME=mosquitto
      - MQTT_WS_PORT=9883
      - MQTT_WS_SSL=false
    ports:
      - "80:80"
    volumes:
      - ./:/grafolean/backend/
    networks:
      - grafolean
    container_name:
      grafolean

networks:
  grafolean:
