version: '2.1'
services:

  # This docker-compose.yml is used for building the grafolean/grafolean docker image
  # during development.

  grafolean:
    image: grafolean/grafolean
    build:
      context: ../../
      dockerfile: install/docker-compose/Dockerfile
      args:
        - REACT_APP_BACKEND_ROOT_URL=/api
