version: '2.1'
services:

  db:
    image: postgres:9.6-alpine
    volumes:
      - ./db/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=grafolean
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -U admin -q"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - grafolean

  grafolean:
    build:
      context: ../../
      dockerfile: install/docker-compose/Dockerfile
      args:
        - REACT_APP_BACKEND_ROOT_URL=/api
    image: grafolean/grafolean
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_DATABASE=grafolean
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - GRAFOLEAN_CORS_DOMAINS=http://localhost
    ports:
      - "80:80"
    networks:
      - grafolean

networks:
  grafolean:
