[supervisord]
nodaemon=true

[program:bootstrap]
command=/bin/bash -c "/grafolean/apply_env.sh && service nginx start && supervisorctl start grafolean:*"
autostart=true
autorestart=false

[group:grafolean]
programs=gunicorn

[program:gunicorn]
command=gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b unix:/tmp/gunicorn.sock grafolean:app
directory=/grafolean/backend
autostart=false
autorestart=true
