name: Deploy to Docker Hub

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create CHANGELOG
      env:
        VERSION: ${{ github.ref }}
        GITLAB_API_ACCESS_TOKEN: ${{ secrets.GITLAB_API_ACCESS_TOKEN }}
      run: |
        pwd
        chmod -R go+w frontend/
        ls -altr
        echo "export const VERSION_INFO = { ciCommitTag: '$VERSION' };" > ./frontend/src/VERSION.js
        cat frontend/src/CHANGELOG.json
